repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: requirements-txt-fixer
  - repo: https://github.com/myint/docformatter
    rev: master
    hooks:
      - id: docformatter
        args: [
          "--in-place",
          "--wrap-descriptions=120",
          "--blank",
          "--pre-summary-newline"
        ]
  - repo: local
    hooks:
      - id: black
        name: Black code formatter
        entry: black
        language: python
        types: [ python ]
        args: [
          "--line-length=120",
          "--preview",
          "--exclude=venv/|build/|dist/|__pycache__/",
          "--target-version=py310",
        ]
      - id: isort
        name: Isort code formatter
        entry: isort
        language: python
        types: [ python ]
        args: [
          "--profile=black",
          "--trailing-comma",
          "--line-length=120",
          "--lines-after-imports=2",
          "--force-grid-wrap=0",
          "--use-parentheses",
          "--ensure-newline-before-comments",
          "--skip=__init__.py",
        ]
      - id: flake8
        name: Flake8 code linter
        entry: flake8
        language: python
        types: [ python ]
        args: [
          "--extend-exclude=.git,__pycache__,venv*,__init__.py,build,dist,docs",
          "--max-line-length=120",
          "--ignore=E402,E501,W503,E203,F811",
          "--show-source",
          "--statistics",
          "--jobs=auto",
          "--verbose",
          "--disable-noqa",
          "--max-complexity=10",
        ]
      - id: mypy
        entry: mypy
        name: Mypy static type checker
        language: python
        types: [ python ]
        args: [
          "--ignore-missing-imports",
          "--scripts-are-modules",
          "--show-error-codes",
          "--strict",
          "--disallow-untyped-defs",
          "--disallow-incomplete-defs",
          "--warn-return-any",
          "--warn-unused-configs",
          "--exclude=.venv|venv|venv310|build|dist",
          "--python-version=3.10",
          "--pretty",
        ]
        require_serial: true
        additional_dependencies: []
