repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: requirements-txt-fixer
  - repo: https://github.com/myint/docformatter
    rev: master
    hooks:
      - id: docformatter
        args: [
          "--in-place",
          "--wrap-descriptions=120",
          "--blank",
          "--pre-summary-newline"
        ]
  - repo: local
    hooks:
      - id: black
        name: Black code formatter
        entry: black
        language: python
        types: [ python ]
        args: [
          "--line-length=120",
          "--preview",
          "--exclude=venv/|build/|dist/|__pycache__/",
          "--target-version=py310",
        ]
      - id: flake8
        name: Flake8 code linter
        entry: flake8
        language: python
        types: [ python ]
        args: [
          "--extend-exclude=.git,__pycache__,venv*,__init__.py,build,dist,docs",
          "--max-line-length=120",
          "--ignore=C901,E203,E402,E501,F811,F821,W503",
          "--show-source",
          "--statistics",
          "--jobs=auto",
          "--verbose",
          "--disable-noqa",
          "--max-complexity=10",
        ]
