global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'torchserve'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['host.docker.internal:8082']

  - job_name: 'service'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['host.docker.internal:5001']
