weights_path: null
config_path: null
formats:
  - onnx
  - tensorrt
enable_mixed_precision: true
input_nodes:
  input_ids:
    shape: [1, 77]
    precision: int64
output_nodes:
  last_hidden_state:
    shape: [1, 77, 1280]
    precision: float16
  text_embeds:
    shape: [1, 1280]
    precision: float16
device: cuda:0
repeats: 1000
enable_benchmark: false
enable_visualization: false

executor:
  module: deploy2serve.deployment.projects.kandinsky_2.clip.executor
  class_name: CLIPExecutor
exporter:
  module: deploy2serve.deployment.projects.kandinsky_2.clip.export
  class_name: CLIPExporter

calibration:
  calibration_frames: null
  excluded_frames: [ ]
  labels_generator:
    module: deploy2serve.deployment.core.exporters.calibration.generators.prompts
    class_name: PromptGenerator
  storage:
    module: deploy2serve.deployment.core.exporters.calibration.dataset.zarr_dataset
    class_name: ZarrChunkedDataset
  cache_path: checkpoints/

tensorrt:
  specific:
    log_level: INFO
    precision: int8
    workspace: 1_073_741_824
    flags:
      - TF32
      - DIRECT_IO
      - OBEY_PRECISION_CONSTRAINTS
      - SPARSE_WEIGHTS
    network_creation_flag:
      - EXPLICIT_BATCH
    builder_optimization_level: 5
    tiling_optimization_level: FULL
    profiling_verbosity: NONE
    max_aux_streams: 4
    runtime_platform: null
    compatibility_level: null
    algorithm: ENTROPY_CALIBRATION_2
  enable_timing_cache: true
  enable_calibration_cache: true
  output_file: checkpoints/kandinsky_2/clip/tensorrt/model.plan
  force_rebuild: true

onnx:
  specific:
    keep_initializers_as_inputs: false
    export_params: true
    verbose: null
    input_names: [input_ids]
    output_names: [last_hidden_state, text_embeds]
    opset_version: 21
    training: EVAL
    do_constant_folding: true
  modelopt:
    quant_mode: int8
    calib_method: entropy
    calib_buffer: 1000
    calibration_eps:
      - cuda
      - cpu
      - dml
    op_types_to_quantize:
      - MatMul
    qdq_for_weights: false
    use_external_data_format: false
    keep_intermediate_files: false
  simplify: false
  output_file: checkpoints/kandinsky_2/clip/onnx/model.onnx
  force_rebuild: true
