weights_path: null
config_path: null

formats:
  - onnx
  - tensorrt
enable_mixed_precision: true
input_nodes:
  input_ids:
    shape: [1, 77]
    precision: int64
output_nodes:
  last_hidden_state:
    shape: [1, 77, 1280]
    precision: float16
  text_embeds:
    shape: [1, 1280]
    precision: float16
device: cuda:0
repeats: 1000
enable_benchmark: false
enable_visualization: false

executor:
  module_path: deploy2serve.deployment.projects.kandinsky_2.clip.executor
  class_name: CLIPExecutor
exporter:
  module_path: deploy2serve.deployment.projects.kandinsky_2.clip.export
  class_name: CLIPExporter

tensorrt:
  specific:
    log_level: INFO
    precision: int8
    workspace: 4_294_967_296
    flags:
      - TF32
      - DIRECT_IO
      - OBEY_PRECISION_CONSTRAINTS
      - SPARSE_WEIGHTS
    profiling_verbosity: NONE
    max_aux_streams: 4
    runtime_platform: null
    compatibility_level: null
    tactics: null
    algorithm: ENTROPY_CALIBRATION_2
  dataset:
    calibration_frames: null
    exclude_frames: [ ]
    labels_generator:
      module_path: deploy2serve.deployment.projects.kandinsky_2.prompt_generator
      class_name: PromptGenerator
    data_storage:
      module_path: deploy2serve.deployment.core.exporters.calibration.dataset.zarr_dataset
      class_name: ZarrChunkedDataset
  enable_timing_cache: true
  enable_calibration_cache: true
  output_file: checkpoints/kandinsky_2/clip/tensorrt/model.plan
  force_rebuild: true

onnx:
  specific:
    keep_initializers_as_inputs: false
    export_params: true
    verbose: null
    input_names: [input_ids]
    output_names: [last_hidden_state, text_embeds]
    opset_version: 19
    training: EVAL
    do_constant_folding: true
#  modelopt:
#    quant_mode: fp8
#    calib_method: max
#    calib_buffer: 500
#    calibration_eps:
#      - cuda
#      - cpu
#      - dml
#    op_types_to_quantize:
#      - Conv
#      - MatMul
#    nodes_to_exclude:
#      - /Shape
#      - /LayerNormalization
#    qdq_for_weights: false
#    use_external_data_format: false
#    keep_intermediate_files: false
  simplify: false
  output_file: checkpoints/kandinsky_2/clip/onnx/model.onnx
  force_rebuild: true
