weights_path: null
config_path: null
formats:
  - onnx
  - tensorrt
enable_mixed_precision: true
input_nodes:
  latent:
    shape: [1, 4, 96, 96]
    precision: float16
output_nodes:
  prediction:
    shape: [1, 3, 768, 768]
    precision: float16
device: cuda:0
repeats: 100
enable_benchmark: false
enable_visualization: false

executor:
  module: deploy2serve.deployment.projects.kandinsky_2.movq.executor
  class_name: MOVQExecutor
exporter:
  module: deploy2serve.deployment.projects.kandinsky_2.movq.export
  class_name: MOVQExporter

calibration:
  calibration_frames: 1000
  excluded_frames: [ ]
  labels_generator:
    module: deploy2serve.deployment.core.exporters.calibration.generators.prompts
    class_name: PromptGenerator
  storage:
    module: deploy2serve.deployment.core.exporters.calibration.dataset.zarr_dataset
    class_name: ZarrChunkedDataset
  cache_path: checkpoints/

tensorrt:
  specific:
    log_level: INFO
    precision: int8
    workspace: 5_368_709_120
    profile_shapes:
      latent:
        - min: [1, 4, 32, 32]
          opt: [2, 4, 64, 64]
          max: [4, 4, 96, 96]
    flags:
      - TF32
      - DIRECT_IO
      - OBEY_PRECISION_CONSTRAINTS
      - SPARSE_WEIGHTS
    builder_optimization_level: 3
    profiling_verbosity: NONE
    max_aux_streams: 4
    runtime_platform: null
    compatibility_level: null
    algorithm: ENTROPY_CALIBRATION_2
  enable_timing_cache: true
  enable_calibration_cache: true
  output_file: checkpoints/kandinsky_2/movq/tensorrt/model.plan
  force_rebuild: true

onnx:
  specific:
    keep_initializers_as_inputs: false
    export_params: true
    verbose: null
    input_names: [latent]
    output_names: [prediction]
    opset_version: 20
    dynamic_axes:
      latent:
        0: batch
        2: height
        3: width
    training: EVAL
    do_constant_folding: true
  modelopt:
    quant_mode: int8
    calib_method: entropy
    calibration_eps:
      - cuda
      - cpu
      - dml
    op_types_to_quantize:
      - MatMul
      - Resize
    qdq_for_weights: false
    use_external_data_format: false
    keep_intermediate_files: false
  simplify: true
  output_file: checkpoints/kandinsky_2/movq/onnx/model.onnx
  force_rebuild: true
