weights_path: null
config_path: null

formats:
  - onnx
  - tensorrt
enable_mixed_precision: true
input_nodes:
  latent:
    shape: [2, 4, 96, 96]
    precision: float16
  timestep:
    shape: [1,]
    precision: int64
  image_embeds:
    shape: [2, 1280]
    precision: float16
output_nodes:
  noise:
    shape: [2, 8, 96, 96]
    precision: float16
device: cuda:0
repeats: 100
enable_benchmark: false
enable_visualization: false

executor:
  module_path: deploy2serve.deployment.projects.kandinsky_2.unet.executor
  class_name: UnetExecutor
exporter:
  module_path: deploy2serve.deployment.projects.kandinsky_2.unet.export
  class_name: UnetExporter

tensorrt:
  specific:
    log_level: INFO
    precision: int8
    workspace: 2_684_354_560
    flags:
      - TF32
      - DIRECT_IO
      - OBEY_PRECISION_CONSTRAINTS
      - SPARSE_WEIGHTS
    builder_optimization_level: 5
    tiling_optimization_level: FULL
    profiling_verbosity: NONE
    max_aux_streams: 4
    runtime_platform: null
    compatibility_level: null
    algorithm: ENTROPY_CALIBRATION_2
  dataset:
    calibration_frames: null
    exclude_frames: [ ]
    labels_generator:
      module_path: deploy2serve.deployment.core.exporters.calibration.generators.prompts
      class_name: PromptGenerator
    data_storage:
      module_path: deploy2serve.deployment.core.exporters.calibration.dataset.zarr_dataset
      class_name: ZarrChunkedDataset
  enable_timing_cache: true
  enable_calibration_cache: true
  output_file: checkpoints/kandinsky_2/unet/tensorrt/model.plan
  force_rebuild: true

onnx:
  specific:
    keep_initializers_as_inputs: false
    export_params: true
    verbose: null
    input_names: [latent, timestep, image_embeds]
    output_names: [noise]
    opset_version: 21
    training: EVAL
    do_constant_folding: true
  modelopt:
    quant_mode: int8
    calib_method: entropy
    calib_buffer: 1000
    calibration_eps:
      - cuda
      - cpu
      - dml
    op_types_to_quantize:
      - MatMul
      - Gemm
      - Resize
      - AveragePool
    qdq_for_weights: false
    use_external_data_format: false
    keep_intermediate_files: true
  simplify: false
  output_file: checkpoints/kandinsky_2/unet/onnx/model.onnx
  force_rebuild: false
