version: '3.8'

services:
  triton:
    container_name: triton
    image: nvcr.io/nvidia/tritonserver:25.05-py3
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    restart: always
    volumes:
      - ${PWD}/triton/models:/models
    command: [ tritonserver, --model-store=/models, --exit-on-error=false, --model-control-mode=poll ]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: 1
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    restart: always
