# For triton api version which not implement ensemble strategy
fastapi:
  host: 127.0.0.1
  port: 5001
triton:
  host: 127.0.0.1
  port: 8001
protocol: grpc
server:
  module: deploy2serve.triton.projects.yolo.server
  cls: RegularYoloTriton
