name: "postprocess"
backend: "python"
max_batch_size: 8

input [
  {
    name: "INPUT__0",
    data_type: TYPE_FP16,
    dims: [ 84, 5040 ]
  },
  {
    name: "INPUT__1",
    data_type: TYPE_FP16,
    dims: [ 2 ]
  }
]

output [
  {
    name: "OUTPUT__0",
    data_type: TYPE_FP16,
    dims: [ 300, 6 ]
  }
]
instance_group [
  {
    kind: KIND_GPU,
    gpus: [0]
  }
]
