global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'triton'
    static_configs:
      - targets: ['triton:8002']

  - job_name: 'ensemble-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5001']
