{
 "title": "Triton Dash",
 "description": "Nvidia GPU Metrics based on the prometheus metrics from github.com/utkuozdemir/nvidia_gpu_exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(nvidia_smi_index,job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(nvidia_smi_index{job=\"$job\"},instance)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(nvidia_smi_index{instance=\"$node\"},uuid)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "nv_cpu_memory_used_bytes{job=\"$job\"} / (1024^3)",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "description": "Current usage of central processor unit as a percentage",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nv_cpu_utilization{job=\"$job\"} * 100"
    }
   ]
  },
  {
   "title": "Power",
   "type": "gauge",
   "description": "Video card power consumption.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nv_gpu_power_usage{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "description": "Current usage of video card resources as a percentage",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_gpu_utilization{job=\"$job\"} * 100",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "GPU Memory usage",
   "type": "timeseries",
   "description": "Video memory consumption.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "nv_gpu_memory_used_bytes{job=\"$job\"} / (1024^3)",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  { "title": "Request metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Inferences per second",
   "type": "timeseries",
   "description": "Number of inferences performed (does not include cached requests), return number inferences per second.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "targets": [
    {
     "expr": "sum by (model,version) (rate(nv_inference_count{job=\"$job\"}[5s]))",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Number of successful requests",
   "type": "timeseries",
   "description": "Number of successful inference requests, all batch sizes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nvidia_smi_power_draw_watts{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    },
    { "expr": "nv_inference_request_success" }
   ]
  },
  {
   "title": "Batch size during inference",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (model,version) (rate(nv_inference_count{job=\"$job\"}[5s])/rate(nv_inference_exec_count{job=\"$job\"}[5s]) )",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Number of failed inference requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "nv_inference_request_failure" }
   ]
  },
  {
   "title": "Total predict requests count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "predict_request_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time spent processing predict request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(predict_request_processing_seconds_sum{job=\"ensemble-service\"}[5s]) \r\n/ \r\nrate(predict_request_processing_seconds_count{job=\"ensemble-service\"}[5s])",
     "legendFormat": "{{uuid}}"
    }
   ]
  }
 ]
}