formats:
  - onnx
  - tensorrt
input_shape: [384, 640]
device: "cuda:0"
repeats: 1000
enable_benchmark: true
enable_visualization: true
tensorrt:
  plugins:
    - name: "efficient_nms"
      options:
        max_det: 75
        score_threshold: 0.25
        iou_threshold: 0.4
  specific:
    log_level: "INFO"
    precision: "fp16"
    profile_shapes:
      - min: [1, 3, 384, 640]
        opt: [1, 3, 384, 640]
        max: [1, 3, 384, 640]
    workspace: 268435456
    flags:
      - "TF32"
      - "DIRECT_IO"
      - "PREFER_PRECISION_CONSTRAINTS"
      - "SPARSE_WEIGHTS"
    profiling_verbosity: "NONE"
    max_aux_streams: 4
    runtime_platform: null
    compatibility_level: null
    tactics: null
    algorithm: "ENTROPY_CALIBRATION_2"
  enable_timing_cache: true
  enable_calibration_cache: true
  output_file: "weights/tensorrt/model.engine"
  force_rebuild: true
onnx:
  specific:
    keep_initializers_as_inputs: false
    export_params: true
    verbose: null
    input_names: ["images"]
    output_names: ["output"]
    opset_version: 11
    dynamic_axes: null
    training: "EVAL"
    do_constant_folding: true
  simplify: true
  output_file: "weights/onnx/model.onnx"
  force_rebuild: true
